apiVersion: v1
kind: Service
metadata:
  labels:
    app: dns
  name: dns
  namespace: kube-system
spec:
  clusterIP: 10.1.0.2
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  selector:
    k8s-app: kube-dns
  type: ClusterIP
