apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: subnets.coyle.club
spec:
  group: coyle.club
  names:
    kind: Subnet
    listKind: SubnetList
    plural: subnets
    shortNames:
      - sn
    singular: subnet
  scope: Cluster
  versions:
    - name: v1
      additionalPrinterColumns:
        - jsonPath: .spec.subnet
          name: Subnet
          type: string
      schema:
        openAPIV3Schema:
          description: ""
          type: object
          required:
            - spec
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: Desired state of the Subnet resource.
              type: object
              required:
                - subnet
              properties:
                subnet:
                  description: ""
                  type: string
      served: true
      storage: true