apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: subdomains.coyle.club
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: coyle.club
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      additionalPrinterColumns:
        - jsonPath: .spec.target
          name: Target
          type: string
        - jsonPath: .spec.public
          name: Public
          type: boolean
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                public:
                  type: boolean
                target:
                  type: string
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: subdomains
    # singular name to be used as an alias on the CLI and for display
    singular: subdomain
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Subdomain
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - sub
---
apiVersion: coyle.club/v1
kind: Subdomain
metadata:
  name: grafana
spec:
  target: grafana.monitoring.svc.coyle.club